language: python
python:
  - "3.10.6"
before_install:
  - sudo /etc/init.d/postgresql start 9.4
before_script:
  - psql -c 'create database routes_api_python_test;' -U postgres
addons:
  postgresql: "9.4.1"
env:
  - APP_SETTINGS=config.DevelopmentConfig DATABASE_URL=postgresql://localhost/routes_api_python_test
install: "pip install -r requirements.txt"
script: coverage run --source app tests.py
after_success:
  - coveralls
