"""empty message

Revision ID: 2620df0c61c
Revises: None
Create Date: 2015-11-22 19:49:31.553624

"""

# revision identifiers, used by Alembic.
revision = '2620df0c61c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('origin_point', sa.String(length=128), nullable=False),
    sa.Column('destination_point', sa.String(length=128), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('origin_point', 'destination_point', 'distance')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    ### end Alembic commands ###
